### ISSUE TITLE
DataLake Export does not include extensions

### ISSUE THREAD

**Issue by torstenfinndorf** [microsoft/Dynamics-365-FastTrack-Implementation-Assets#131]
The export to the Lake does not include extensions.
If i have extended the string size of ItemIdBase from 20 to 50 the cdm.json of the table only include the size of 20 for the column ItemId.
Is it possible to export the extended size of datatypes?

**Comment by jiyada** [comment]
Metadata files i.e cdm.json is created by Export to data lake service/enhanced metadata service that is part of Dynamics 365 Finance and Operations. This seems like a product bug please raise a support request so that team can investigate the issue. CDMutil is just reading the metadata as exists in the cdm.json file.
