### ISSUE TITLE
Could not read '/Tables.manifest.cdm.json' 

### ISSUE THREAD

**Issue by dspriggs-ds** [microsoft/Dynamics-365-FastTrack-Implementation-Assets#171]
Working with a customer they have implemented the Azure Function. When running the Azure Function via the Storage Account event we encounter the following error

Could not read '/Tables.manifest.cdm.json' from the 'adls' namespace. Reason 'HTTP NotFound - The specified path does not exist.. Response headers: Server:Windows-Azure-HDFS/1.0,Microsoft-HTTPAPI/2.0, x-ms-error-code:PathNotFound, x-ms-request-id:285536ab-001f-0050-25e1-e36070000000, x-ms-version:2018-03-28

We checked the function did have Storage Blob Data Reader and Contributor access. As well we set the ManifestURL correctly. 

Thoughts?

**Comment by jiyada** [comment]
I believe the latest version of the function app logs the complete url of the blob before reading the cdm files. Are you able to see the log to see if the path is correct ? Also when using the Storage event you should restrict the events to .cdm.json files and not trigger on .manifest.cdm.json so that individual tables can trigger schema generation.

**Comment by Geniusinhd87** [comment]
@jiyada have you gotten the storage trigger working? if so do you mind helping. I see the eventgrid registering. But the storage trigger never runs the pipeline.
