### ISSUE TITLE
CDMUtil to Delta Lake

### ISSUE THREAD

**Issue by BlueMonday-Donovan-Wilson** [microsoft/Dynamics-365-FastTrack-Implementation-Assets#61]
Is there an implementation/configuration by which the CDMUtil can create Delta Lake Tables?

**Comment by jiyada** [comment]
Export to data lake feature of Dynamics 365 export tables data as CSV and metadata as CDM. UDMUtil is intended to convert the CDMMetadata to target endpoint format for example TSQL DDL to create OpenRowSet view , external table or Synapse Table so that you can query the data using TSQL or Spark.  
Delta Lake is more of data format. If your plan is to create delta lake format from D365 data, you can use Data Flow  from ADF or Synapse pipeline to convert CSV data into delta lake format.
